apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: test-bucket
  namespace: test
spec:
  generateBucketName: test-bkt
  storageClassName: rgw-s3 # CHANGEME
  additionalConfig:
    # # To set for quota for OBC
    # maxObjects: "1000"
    # maxSize: "2G"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obc-test-pod
  namespace: test
  labels:
    app: obc-test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obc-test-pod
  template:
    metadata:
      labels:
        app: obc-test-pod
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      # serviceAccountName: rook-ceph-default
      #securityContext:
      #  allowPrivilegeEscalation: false
      containers:
        - name: obc-test
          image: d3fk/s3cmd
          command:
            - sleep
            - infinity
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: test-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: test-bucket
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_CA_BUNDLE
              value: /cabundle/service-ca.crt
            - name: BUCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-bucket
                  key: BUCKET_HOST
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: test-bucket
                  key: BUCKET_NAME
            - name: BUCKET_PORT
              valueFrom:
                configMapKeyRef:
                  name: test-bucket
                  key: BUCKET_PORT
        - name: net-test
          image: jonlabelle/network-tools
          command:
            - sleep
            - infinity
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      # tolerations:
      #   - key: "node.kubernetes.io/unreachable"
      #     operator: "Exists"
      #     effect: "NoExecute"
      #     tolerationSeconds: 5

# Test dns (from net-test pod)
#   dig @odf-dns.rook-ceph.svc *.ceph-s3.data.local

# TO TEST:
#   s5cmd --endpoint-url https://$BUCKET_HOST:443 ls s3://$BUCKET_NAME
#   echo "Hello Rook" > /tmp/hello
#   s5cmd --endpoint-url https://$BUCKET_HOST:443 cp /tmp/hello s3://$BUCKET_NAME
#   rm /tmp/hello
#   s5cmd --endpoint-url https://$BUCKET_HOST:443 cp s3://$BUCKET_NAME/hello /tmp/hello
#   cat /tmp/hello
